# -*- coding: utf-8 -*-
"""the_lista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWcuoF6zl8uOFLQXxPjYL7nJE6O1eny2

# "The Lista"
Digitalisoitu Ilkka Parviaisen The Lista ranking. Kirjoitettu Python koodiksi perustuen Yahoo Finance dataan.

Hienoisia eroja
PE = taakse katsova päivän kurssilla
ROE = 4Q taakse katsova
Datalähde on eri, joten se voi tuoda myös pieniä eroja listan järjestykseen. Listan pisteytys on sama, eli tasapisteillä kaikki saavat korkeimman sijaluvun, ja seuraava eri pisteille tuleva sijaluku on tasapisteet saaneiden määrän verran edellistä pistelukua suurempi (1, 2, 2, 4, 5, 5, 5, 8, esimerkiksi). Pisteytykset lasketaan täysillä desimaaleilla, ja pyöristetään taulukon tulostuksen yhteydessä.

Kommentit englanniksi, koska koodia, ja selitteet suomeksi, koska lukija.

*Willem van Schevikhoven*

Ensimmäinen osa lataa kirjastoja. Tässä voi poistaa tickers -muuttujan edestä kommentin, eli vaihtaa nopeasti sitä mitä listaa analysoidaan.
"""

import yfinance as yf
import pandas as pd
import numpy as np
import streamlit as st

# Set display width to some more
pd.set_option('display.width', 360)

history_period = '3y'
history_interval = '1d'
framesize = 20
bollinger_mult = 2.5

tickers = ["AALLON.HE", "ADMCM.HE", "ADMIN.HE", "AIFORIA.HE", "ALEX.HE", "ARVOSK.HE", "ASUNTO.HE", "BETOLAR.HE", "BRETEC.HE", "CANATU.HE", "DETEC.HE", "DWF.HE", "DUELL.HE", "EAGLE.HE", "ECOUP.HE", "FARON.HE", "FODELIA.HE", "FONDIA.HE", "HRTIS.HE", "INDERES.HE", "LAPWALL.HE", "LEADD.HE", "LEMON.HE", "LOIHDE.HE", "MERUS.HE", "MODU.HE", "NANOFH.HE", "NETUM.HE", "NXTMH.HE", "BEER.HE", "NORRH.HE", "PALLAS.HE", "PIIPPO.HE", "SFOODS.HE", "SOLWERS.HE", "SPINN.HE", "SPRING.HE", "SUMMA.HE", "SBI.HE", "TAMTRON.HE", "TEKOVA.HE", "TITAN.HE", "VIAFIN.HE", "VINCIT.HE", "WITTED.HE", "AKTIA.HE", "ELISA.HE", "FORTUM.HE", "HIAB.HE", "HUH1V.HE", "KALMAR.HE", "KEMIRA.HE", "KESKOB.HE", "KOJAMO.HE", "KNEBV.HE", "KCR.HE", "MANTA.HE", "METSO.HE", "NESTE.HE", "NOKIA.HE", "TYRES.HE", "NDA-FI.HE", "ORNBV.HE", "OUT1V.HE", "QTCOM.HE", "SAMPO.HE", "STERV.HE", "TIETO.HE", "UPM.HE", "VALMT.HE", "WRT1V.HE"]

@st.cache_data
def fetchMasterData(tickers, history_period, history_interval):
    # Init the dataframe
    df = pd.DataFrame()
    # Loop through tickers to get stock data from yfinance
    for ticker_symbol in tickers:
        oTicker = yf.Ticker(ticker_symbol)
        dfHistory = oTicker.history(period=history_period, interval=history_interval).add_prefix(ticker_symbol + "_")
        df = df.merge(dfHistory, how='outer', left_index=True, right_index=True)
    return df

def calculateMetrics(df, tickers, framesize, bollinger_mult):
    dfTmp = pd.DataFrame()
    for ticker in tickers:
        dfTmp[ticker + '_SMA'] = df[ticker + '_Close'].rolling(window=framesize).mean()
        dfTmp[ticker + '_SD'] = df[ticker + '_Close'].rolling(window=framesize).std()
        dfTmp[ticker + '_BOLLINGER_U'] = dfTmp[ticker + '_SMA'] + (bollinger_mult * dfTmp[ticker + '_SD'])
        dfTmp[ticker + '_BOLLINGER_L'] = dfTmp[ticker + '_SMA'] - (bollinger_mult * dfTmp[ticker + '_SD'])
    return df.merge(dfTmp, how='inner', left_index=True, right_index=True)

dfHist = fetchMasterData(tickers, history_period, history_interval)
dfHist = calculateMetrics(dfHist.copy(deep=True), tickers, framesize, bollinger_mult)

@st.cache_data
def get_stock_info(tickers_list, _df_hist):
    info_df = pd.DataFrame(columns =  ["Name @PreviousClose", "ROE", "PE", "PB", "DIV", "BBPos"])
    for ticker_symbol in tickers_list:
        oTicker = yf.Ticker(ticker_symbol).info
        prev_close = oTicker.get("previousClose", np.nan)
        sma = _df_hist[ticker_symbol.upper()+"_SMA"].iloc[-1] if ticker_symbol.upper()+"_SMA" in _df_hist else np.nan
        boll_l = _df_hist[ticker_symbol.upper()+"_BOLLINGER_L"].iloc[-1] if ticker_symbol.upper()+"_BOLLINGER_L" in _df_hist else np.nan
        
        bbpos = np.nan
        if not pd.isna(prev_close) and not pd.isna(sma) and not pd.isna(boll_l) and (sma - boll_l) != 0:
             bbpos = (prev_close - sma) / (sma - boll_l)

        info_df.loc[ticker_symbol] = [
            oTicker.get("shortName", ticker_symbol) + " @" + str(prev_close),
            oTicker.get("returnOnEquity", np.nan),
            oTicker.get("trailingPE", np.nan),
            oTicker.get("priceToBook", np.nan),
            oTicker.get("trailingAnnualDividendYield", np.nan),
            bbpos
        ]
    return info_df

dfInfo = get_stock_info(tickers, dfHist)

metrics = {
  "ROE": False,
  "DIV": False  
}

for col, ascend in metrics.items():
    rank_col = f"{col}_Rank"
    dfInfo[rank_col] = (dfInfo[col].rank(method="min", ascending=ascend, na_option="bottom").astype(int))

pe_for_rank = dfInfo['PE'].where(dfInfo['PE'] > 0, np.inf)
pb_for_rank = dfInfo['PB'].where(dfInfo['PB'] > 0, np.inf)

dfInfo['PE_Rank'] = (pe_for_rank.rank(method='min', ascending=True, na_option='bottom').astype(int))
dfInfo['PB_Rank'] = (pb_for_rank.rank(method='min', ascending=True, na_option='bottom').astype(int))

rank_cols = ["PE_Rank", "PB_Rank", "ROE_Rank", "DIV_Rank"]
dfInfo["Total_Rank"] = dfInfo[rank_cols].sum(axis=1)
dfInfo = dfInfo.sort_values("Total_Rank", ascending=True)

df_print = dfInfo.copy()
df_print['PE'] = df_print['PE'].apply(lambda x: "-" if pd.isna(x) else f"{x:.2f}")
df_print['PB'] = df_print['PB'].apply(lambda x: "-" if pd.isna(x) else f"{x:.2f}")
df_print['ROE'] = df_print['ROE'].apply(lambda x: "-" if pd.isna(x) else f"{x * 100:.2f} %")
df_print['BBPos'] = df_print['BBPos'].apply(lambda x: "-" if pd.isna(x) else f"{x * 100:.2f} %")
df_print['DIV'] = df_print['DIV'].apply(lambda x: "-" if pd.isna(x) else f"{x * 100:.2f} %")

st.title('The Lista - Osake Ranking')
st.write('Digitalisoitu Ilkka Parviaisen The Lista ranking.')
st.dataframe(df_print, use_container_width=True)